### ISSUE TITLE
I am loggin in MEGAcmd 

### ISSUE THREAD

**Issue by sxocker** [ritiek/plugin.video.megacmd#1]
But i can open the addon
   Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 2] El sistema no puede encontrar el archivo especificado
                                            Traceback (most recent call last):
                                              File "C:\Users\PC\AppData\Roaming\Kodi\addons\plugin.video.megacmd\addon.py", line 2, in <module>
                                                from resources import megacmd
                                              File "C:\Users\PC\AppData\Roaming\Kodi\addons\plugin.video.megacmd\resources\megacmd.py", line 8, in <module>
                                                subprocess.call(MEGA_CMD_PATH + "-" + "ls")
                                              File "C:\Program Files\Kodi\system\python\Lib\subprocess.py", line 168, in call
                                                return Popen(*popenargs, **kwargs).wait()
                                              File "C:\Program Files\Kodi\system\python\Lib\subprocess.py", line 390, in __init__
                                                errread, errwrite)
                                              File "C:\Program Files\Kodi\system\python\Lib\subprocess.py", line 640, in _execute_child
                                                startupinfo)
                                            WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado
                                            -->End of Python script error report<--
2019-06-21 20:54:23.836 T:1448   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.megacmd/
2019-06-21 20:54:23.839 T:10000   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.megacmd/) failed

**Comment by ritiek** [comment]
Oooo, I see. I've only tried this on Linux. I'll check for Windows soon.

**Comment by sxocker** [comment]
> Oooo, I see. I've only tried this on Linux. I'll check for Windows soon.

thanks for responding
